### PR TITLE
update dependencies' version

### PR DESCRIPTION
**Pull request by swhgoon**

### CODE REVIEW

**Comment by amark** [comment]
cool, thanks @swhgoon ! :) How is your project going?

**Comment by swhgoon** [comment]
@amark 
try to customize UUID now...
> "But if you do have this problem, consider giving each one of your sub-objects a deterministic ID."
> https://github.com/amark/gun/wiki/API#get

**Comment by amark** [comment]
@swhgoon give me more context / background? What are you trying to do? Because it should automatically merge with existing data (unless you are forcing it, or you are disconnected, etc.)

**Comment by swhgoon** [comment]
@amark 
solved by reducing object's levels from 3 to 2...
it seems caused by delay between gun and sqlite

**Comment by amark** [comment]
@swhgoon I was very disappointed in  SQLite's performance, it seems to be in "synchronous" mode where all writes are written to disk which causes it to be VERY slow. Even turning it off didn't help much. :(

**Pull request merged**
