### PR TITLE
Readme.md: + option for sqlite's file

### PR DESCRIPTION
**Pull request by swhgoon**
got from source:)

### CODE REVIEW

**Comment by amark** [comment]
@swhgoon you rock! Pulling. What are you working on / building?

**Comment by swhgoon** [comment]
I try to replace all SQL in my old programs with GunDB:)

**Comment by amark** [comment]
@swhgoon wow! How is it going? Anything I can help with? What are your programs?

**Comment by swhgoon** [comment]
testing it as a local db 1st:
a simple program stores feed entries, filtered and converted to ebooks later.

try to write a function opposite to `gun.set` now...

BTW: I updated from `0.3` because this module:)

**Comment by amark** [comment]
@swhgoon great to hear! Sounds cool, have a demo anywhere I can see??

Have you seen all of stefdv's tagging libraries, they work nicely as an "opposite" to `set` as well, tagging seems to be like a more efficient way to filter things than using sets.

Hey, have you had any performance problems with this module? I haven't run any benchmarks yet.

**Comment by swhgoon** [comment]
@amark 
stefdv's tagging library seems patch the original data <= `this.path('tags').put(t)`

I wrote a different tag module with `scala-js`, separate
 but depend on data's custom-build id, which may change to gun's build-in id.

======
Sorry for replay later, i am unfamiliar with `javascript` and reading code slowly...
I found `prefix` useful in gun's option from your codes:), which not listed in wiki.

======
// stucked in looking for reusing gun's websocket in browser context,
// I saw `module.exports = Client;` in code...
:-) solved by 
`gun.on("in", ...)`
and
`Gun.on("out", ...)`

**Comment by amark** [comment]
@swhgoon I'm not sure I understand what you are saying, but what I did makes me curious to learn more.

Are your edits/changes published in your github repo? Should I look/read there?

**Comment by amark** [comment]
I couldn't find your new tagging module? Do you have it published?

**Comment by swhgoon** [comment]
haven't sparated from local project...

**Pull request merged**
